Repaired unwanted dependency with org.apache.commons.pool.PoolableObjectFactory (caused NoClassDefFoundError for OxygenXml). Errors are ignored (and logged)
svn path=/trunk/eXist/; revision=5674