[feature] add missing OxygenXML libs to fix `Check datasource configuration. Could not instantiate: ro.sync.db.nxd.exist.ExistSession due to: java.lang.NoClassDefFoundError: xyz/elemental/mediatype/MediaType`